name: docker-build-push-latest
on:
  workflow_dispatch:
  push:
        
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          platforms: linux/arm64
          context: .
          push: true
          tags: dotwee/matrix-media-repo:latest
          file: Dockerfile.arm64
          labels: |
            maintainer = "Lukas Wolfsteiner <lukas@wolfsteiner.media>"
            org.opencontainers.image.source = "https://github.com/dotWee/docker-matrix-media-repo"
